// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBweYiPuM0coJFv-o2cIMUKMfdJgP-Sghw',
    appId: '1:676233475204:web:b0b78233a9b22803cc3ed1',
    messagingSenderId: '676233475204',
    projectId: 'quizapp-bdf53',
    authDomain: 'quizapp-bdf53.firebaseapp.com',
    storageBucket: 'quizapp-bdf53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYI_QlwqsUjO6WywYQ1XKwosx6JfHTghQ',
    appId: '1:676233475204:android:a007449243623470cc3ed1',
    messagingSenderId: '676233475204',
    projectId: 'quizapp-bdf53',
    storageBucket: 'quizapp-bdf53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2XCN562kpeX_EScWseTfcDZU2O4Z52iM',
    appId: '1:676233475204:ios:9bd6152456d38ac8cc3ed1',
    messagingSenderId: '676233475204',
    projectId: 'quizapp-bdf53',
    storageBucket: 'quizapp-bdf53.firebasestorage.app',
    iosBundleId: 'com.example.quizAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2XCN562kpeX_EScWseTfcDZU2O4Z52iM',
    appId: '1:676233475204:ios:9bd6152456d38ac8cc3ed1',
    messagingSenderId: '676233475204',
    projectId: 'quizapp-bdf53',
    storageBucket: 'quizapp-bdf53.firebasestorage.app',
    iosBundleId: 'com.example.quizAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBweYiPuM0coJFv-o2cIMUKMfdJgP-Sghw',
    appId: '1:676233475204:web:277b3264415c1d79cc3ed1',
    messagingSenderId: '676233475204',
    projectId: 'quizapp-bdf53',
    authDomain: 'quizapp-bdf53.firebaseapp.com',
    storageBucket: 'quizapp-bdf53.firebasestorage.app',
  );
}
